name: CI/CD Pipeline for Mobile App

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (assuming the mobile app is a React Native app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust based on your project needs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build (adjust this for your mobile app)
      - name: Build the app
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run automated tests
        run: npm test

      # Step 5: Notify user of test results (slack, email, etc.)
      - name: Send Notification on Failure
        if: failure()
        run: echo "Tests failed. Please check the logs."
